<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Loading-Librarys-and-data" data-toc-modified-id="Loading-Librarys-and-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Loading Librarys and data</a></span><ul class="toc-item"><li><span><a href="#Cross-Validation-with-KFOLD-and-Hyperpaqrameter-Tuning" data-toc-modified-id="Cross-Validation-with-KFOLD-and-Hyperpaqrameter-Tuning-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Cross Validation with KFOLD and Hyperpaqrameter Tuning</a></span></li></ul></li><li><span><a href="#balancing-data-using-random-forest" data-toc-modified-id="balancing-data-using-random-forest-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>balancing data using random forest</a></span></li><li><span><a href="#different-sampling-using-imblearn-library" data-toc-modified-id="different-sampling-using-imblearn-library-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>different sampling using imblearn library</a></span><ul class="toc-item"><li><span><a href="#Under-Sampling" data-toc-modified-id="Under-Sampling-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Under Sampling</a></span></li><li><span><a href="#Over-Sampling" data-toc-modified-id="Over-Sampling-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Over Sampling</a></span></li><li><span><a href="#SMOTETomek" data-toc-modified-id="SMOTETomek-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>SMOTETomek</a></span></li><li><span><a href="#Ensemble-Techniques" data-toc-modified-id="Ensemble-Techniques-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Ensemble Techniques</a></span></li></ul></li></ul></div>

# Loading Librarys and data

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_pickle("Datafiles/creditcard.pkl")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.shape

(284807, 31)

In [4]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [5]:
# Independent and Dependent Features
X=df.drop("Class",axis=1)
y=df.Class

## Cross Validation with KFOLD and Hyperpaqrameter Tuning

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [7]:
10.0 **np.arange(-2,3)

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [23]:
log_class = LogisticRegression(max_iter=500)
grid={'C':10.0 **np.arange(-2,3),'penalty':['l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7)

In [25]:
clf = GridSearchCV(log_class, grid, cv=cv, n_jobs=-1, scoring='f1_macro')
clf.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(max_iter=500), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l2']},
             scoring='f1_macro')

In [26]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85266    17]
 [   63    97]]
0.9990637032875719
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85283
           1       0.85      0.61      0.71       160

    accuracy                           1.00     85443
   macro avg       0.93      0.80      0.85     85443
weighted avg       1.00      1.00      1.00     85443



# balancing data using random forest

In [27]:
y_train.value_counts()

0    199032
1       332
Name: Class, dtype: int64

In [28]:
332*100

33200

In [29]:
class_weight=dict({0:1, 1:100})

In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [31]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85278     5]
 [   46   114]]
0.999403110845827
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85283
           1       0.96      0.71      0.82       160

    accuracy                           1.00     85443
   macro avg       0.98      0.86      0.91     85443
weighted avg       1.00      1.00      1.00     85443



# different sampling using imblearn library

## Under Sampling
Undersampling is appropriate when there is plenty of data for an accurate analysis

In [32]:
from collections import Counter
Counter(y_train)

Counter({0: 199032, 1: 332})

In [36]:
# in Under Sampling value with higher class gets reduced
from collections import Counter
from imblearn.under_sampling import NearMiss
ns = NearMiss(sampling_strategy=0.8)
X_train_ns, y_train_ns = ns.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199032, 1: 332})
The number of classes after fit Counter({0: 415, 1: 332})


In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [38]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[69880 15403]
 [   18   142]]
0.8195171049705652
              precision    recall  f1-score   support

           0       1.00      0.82      0.90     85283
           1       0.01      0.89      0.02       160

    accuracy                           0.82     85443
   macro avg       0.50      0.85      0.46     85443
weighted avg       1.00      0.82      0.90     85443



## Over Sampling
Over sampling is used when the amount of data collected is insufficient

In [39]:
from imblearn.over_sampling import RandomOverSampler

In [41]:
# in Over Sampling, lesser class gets increase in weights
os=RandomOverSampler(sampling_strategy=0.75)
X_train_ns, y_train_ns = os.fit_resample(X_train, y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199032, 1: 332})
The number of classes after fit Counter({0: 199032, 1: 149274})


In [42]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [43]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85277     6]
 [   43   117]]
0.9994265182636377
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85283
           1       0.95      0.73      0.83       160

    accuracy                           1.00     85443
   macro avg       0.98      0.87      0.91     85443
weighted avg       1.00      1.00      1.00     85443



## SMOTETomek
Combine over and under sampling using SMOTE and Tomek links

In [44]:
from imblearn.combine import SMOTETomek

In [46]:
os = SMOTETomek(sampling_strategy=0.75)
X_train_ns, y_train_ns = os.fit_resample(X_train,y_train)
print("The number of classes before fit {}".format(Counter(y_train)))
print("The number of classes after fit {}".format(Counter(y_train_ns)))

The number of classes before fit Counter({0: 199032, 1: 332})
The number of classes after fit Counter({0: 198444, 1: 148686})


In [47]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

RandomForestClassifier()

In [48]:
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85271    12]
 [   36   124]]
0.9994382219725431
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85283
           1       0.91      0.78      0.84       160

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## Ensemble Techniques

In [49]:
from imblearn.ensemble import EasyEnsembleClassifier

In [51]:
easy=EasyEnsembleClassifier()
easy.fit(X_train,y_train)

EasyEnsembleClassifier()

In [52]:
y_pred=easy.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[82483  2800]
 [   16   144]]
0.9670423557225285
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     85283
           1       0.05      0.90      0.09       160

    accuracy                           0.97     85443
   macro avg       0.52      0.93      0.54     85443
weighted avg       1.00      0.97      0.98     85443

