### Importing Librarys

In [1]:
import numpy as np
np.__version__

'1.23.1'

### Array

In [2]:
arr = np.array([1,2,52,7,4,7])
arr

array([ 1,  2, 52,  7,  4,  7])

### Instant Array Generation

In [3]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

In [4]:
np.zeros([2, 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# diagonal matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# k is called key, k determines way of column traversing
np.eye(5,5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.eye(5,5, k=-3)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [11]:
# generates empty matrix
np.empty([3,3])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# here 5 is used to fill matrix
np.full([3,3], 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [13]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [15]:
np.linspace(1,2,7)

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [16]:
# If restep is True, returns (samples, step) where step is spacing between samples
np.linspace(2,3,5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
# if endpoint True, stop is last sample Otherwise it is not included, Default is True
np.linspace(2,3,5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [18]:
# generates 2d Matrix
np.meshgrid(np.arange(1, 10, 2), np.arange(1, 10, 2))

[array([[1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9]]),
 array([[1, 1, 1, 1, 1],
        [3, 3, 3, 3, 3],
        [5, 5, 5, 5, 5],
        [7, 7, 7, 7, 7],
        [9, 9, 9, 9, 9]])]

In [19]:
# generating random value, generates one value between 1 and 100
np.random.randint(1, 100)

63

In [20]:
# generating array of random values
np.random.randn(10)

array([-0.09920061, -0.59225565, -0.22179746, -0.14275479,  2.44454187,
       -1.89337887, -0.74032576,  1.61449512, -0.82398934, -0.16543723])

### Types of Arrays

In [21]:
arr = np.random.randn(10)
type(arr), arr.dtype

(numpy.ndarray, dtype('float64'))

In [22]:
# defining type of np array
np.array([1,2,52,7,4,7], dtype=np.int64)

array([ 1,  2, 52,  7,  4,  7], dtype=int64)

In [23]:
np.array([1,2,52,7,4,7], dtype=np.float16)

array([ 1.,  2., 52.,  7.,  4.,  7.], dtype=float16)

In [24]:
# using np.bool_ instead of np.bool as np.bool_ supports array types
np.array([True, False, True, True, False, 0, 1], dtype=np.bool_)

array([ True, False,  True,  True, False, False,  True])

In [25]:
np.array([1,2,52,7,4,7], dtype=np.complex_)

array([ 1.+0.j,  2.+0.j, 52.+0.j,  7.+0.j,  4.+0.j,  7.+0.j])

In [26]:
# b for bytes in output as it stores string in bytes
np.array(['apple', 'python', 'banana', 'grapes'], dtype=np.string_)

array([b'apple', b'python', b'banana', b'grapes'], dtype='|S6')

### Inspect Arrays

In [27]:
arr

array([ 1.23752123,  0.81182882,  1.7712827 ,  1.02845049,  1.33732017,
        0.58968234,  0.56801744,  1.24574163, -0.5145487 ,  0.16406267])

In [28]:
arr.ndim

1

In [29]:
arr2 = np.full([3,3], 5)
arr2.ndim

2

In [30]:
arr.dtype

dtype('float64')

In [31]:
# itemsize is Length of one array element in bytes
arr.itemsize

8

In [32]:
# total element of an array
arr.size

10

In [33]:
arr.shape

(10,)

In [34]:
arr2.shape

(3, 3)

### Slicing and Indexing

In [35]:
arr3 = np.array([
    [23 ,14, 54, 27, 67, 54],
    [22, 56, 29, 70, 23, 67],
    [22, 53, 78, 14, 63, 85],
    [21, 53, 64, 52, 79, 94]
])

In [36]:
arr3.shape

(4, 6)

In [37]:
arr3[0, 2]

54

In [38]:
arr3[1:3, 2:4]

array([[29, 70],
       [78, 14]])

In [39]:
# first 1 indicates slicing will start from row 1
# second 1 indicates slicing will start from coumn 1
# 2 indicates step size
arr3[1:, 1::2]

array([[56, 70, 67],
       [53, 14, 85],
       [53, 52, 94]])

### Filtering

In [40]:
arr3 < 50

array([[ True,  True, False,  True, False, False],
       [ True, False,  True, False,  True, False],
       [ True, False, False,  True, False, False],
       [ True, False, False, False, False, False]])

In [41]:
arr3[arr3 < 50]

array([23, 14, 27, 22, 29, 23, 22, 14, 21])

In [42]:
# getting only odd numbers
arr3[arr3%2 == 1]

array([23, 27, 67, 29, 23, 67, 53, 63, 85, 21, 53, 79])

In [43]:
arr3[(arr3%2 == 1) & (arr3>50)]

array([67, 67, 53, 63, 85, 53, 79])

In [44]:
# Tilde sign ~ works as not condition 
arr3[~(arr3%2 == 1) & (arr3>50)]

array([54, 54, 56, 70, 78, 64, 52, 94])

In [45]:
arr3[~(arr3>50)]

array([23, 14, 27, 22, 29, 23, 22, 14, 21])

### Operators

In [46]:
# numpy broadcasting
arr3 + arr3

array([[ 46,  28, 108,  54, 134, 108],
       [ 44, 112,  58, 140,  46, 134],
       [ 44, 106, 156,  28, 126, 170],
       [ 42, 106, 128, 104, 158, 188]])

In [47]:
arr3 * arr3

array([[ 529,  196, 2916,  729, 4489, 2916],
       [ 484, 3136,  841, 4900,  529, 4489],
       [ 484, 2809, 6084,  196, 3969, 7225],
       [ 441, 2809, 4096, 2704, 6241, 8836]])

In [48]:
arr3 + 5

array([[28, 19, 59, 32, 72, 59],
       [27, 61, 34, 75, 28, 72],
       [27, 58, 83, 19, 68, 90],
       [26, 58, 69, 57, 84, 99]])

In [49]:
arr4 = np.array([
    [23 ,14, 54],
    [22, 56, 29],
    [22, 53, 78],
])

In [50]:
arr4@arr4

array([[2025, 3968, 5860],
       [2376, 4981, 5074],
       [3388, 7410, 8809]])

In [51]:
arr4*arr4

array([[ 529,  196, 2916],
       [ 484, 3136,  841],
       [ 484, 2809, 6084]])

### Load and Save

In [2]:
# to know parameters of save, press Esc to close documentation
# command only works on default jupyter notebook 
# np.save?

Object `np.save` not found.


In [52]:
res = arr4@arr4

In [53]:
# saving res to data.npy file, file can't be be read 
np.save('data.npy', res)

In [54]:
# loading data.npy
np.load('data.npy')

array([[2025, 3968, 5860],
       [2376, 4981, 5074],
       [3388, 7410, 8809]])

In [55]:
# savez use to save multiple array in numpy zip file
# here array arr4 and res are being saved into data.npz file
np.savez('data.npz', ar1=arr4, ar2=res)

In [3]:
data = np.load('data.npz')

In [4]:
data.files

['ar1', 'ar2']

In [5]:
data['ar1']

array([[23, 14, 54],
       [22, 56, 29],
       [22, 53, 78]])

In [6]:
data['ar2']

array([[2025, 3968, 5860],
       [2376, 4981, 5074],
       [3388, 7410, 8809]])

### Statistics with NumPy

In [7]:
matrix = data['ar1']
matrix

array([[23, 14, 54],
       [22, 56, 29],
       [22, 53, 78]])

In [8]:
matrix.mean()

39.0

In [9]:
matrix.sum()

351

In [10]:
# row wise sum
matrix.sum(axis=0)

array([ 67, 123, 161])

In [11]:
# column wise sum
matrix.sum(axis=1)     

array([ 91, 107, 153])

In [12]:
print(matrix.mean())
print(matrix.mean(axis=0))
print(matrix.mean(axis=1))

39.0
[22.33333333 41.         53.66666667]
[30.33333333 35.66666667 51.        ]


In [13]:
# returns True as there is no 0 in matrix
matrix.all()

True

In [14]:
matrix1 = data['ar1']
matrix1[0,1] = 0
matrix1

array([[23,  0, 54],
       [22, 56, 29],
       [22, 53, 78]])

In [15]:
# returns False as there is one 0 in matrix1
matrix1.all()

False

In [16]:
# returns true if any value greater than one
matrix.any()

True

In [17]:
# cumulative sum
matrix.cumsum()

array([ 23,  37,  91, 113, 169, 198, 220, 273, 351])

In [19]:
# cumulative product
matrix1.cumprod()

array([23,  0,  0,  0,  0,  0,  0,  0,  0])

In [20]:
matrix.max(axis=0)

array([23, 56, 78])

In [21]:
matrix.max(axis=1)

array([54, 56, 78])

In [23]:
print(matrix.min(axis=0))
print(matrix.min(axis=1))

[22 14 29]
[14 22 22]


In [24]:
# calculating variance
matrix.var(axis=0)

array([2.22222222e-01, 3.66000000e+02, 4.00222222e+02])

In [25]:
# output is same as std below cell 
np.sqrt(matrix.var(axis=0))

array([ 0.47140452, 19.13112647, 20.00555478])

In [26]:
matrix.std(axis=0)

array([ 0.47140452, 19.13112647, 20.00555478])

In [27]:
# covariance
np.cov(matrix)

array([[ 440.33333333, -194.83333333,  409.5       ],
       [-194.83333333,  322.33333333,  128.5       ],
       [ 409.5       ,  128.5       ,  787.        ]])

In [28]:
np.quantile(matrix, 0.25, axis=0)

array([22. , 33.5, 41.5])

In [29]:
np.quantile(matrix, 0.75, axis=0)

array([22.5, 54.5, 66. ])

### Linear Algebra

In [30]:
from numpy import linalg

In [31]:
linalg.det(matrix)

46457.00000000002

In [32]:
linalg.inv(matrix)

array([[ 0.06093807,  0.03809975, -0.05635319],
       [-0.02320425,  0.01304432,  0.01121467],
       [-0.00142067, -0.01960953,  0.02109478]])

In [33]:
linalg.norm(matrix)

132.20816918783802

In [34]:
# b takes all rows and only last column from matrix
a = matrix
b = matrix[:, -1]
linalg.solve(a, b)

array([0., 0., 1.])

In [35]:
linalg.svd(matrix)

(array([[-0.44073058, -0.61199327,  0.65667404],
        [-0.47883647,  0.77906726,  0.40468487],
        [-0.75925766, -0.13608248, -0.63640346]]),
 array([127.08269403,  34.91984155,  10.46869348]),
 array([[-0.29409885, -0.57620533, -0.76255707],
        [ 0.00199943,  0.79746895, -0.60335667],
        [ 0.95577292, -0.17897119, -0.23338262]]))

In [36]:
linalg.eig(matrix)

(array([124.52524257 +0.j        ,  16.23737872+10.46042474j,
         16.23737872-10.46042474j]),
 array([[ 0.46451561+0.j        ,  0.84565438+0.j        ,
          0.84565438-0.j        ],
        [ 0.46744193+0.j        , -0.39261939-0.27470275j,
         -0.39261939+0.27470275j],
        [ 0.75214579+0.j        , -0.00411424+0.23503227j,
         -0.00411424-0.23503227j]]))

In [37]:
linalg.eigh(matrix)

(array([ 10.34860957,  16.5692369 , 130.08215354]),
 array([[-0.61245287,  0.74006312, -0.27786337],
        [ 0.70660845,  0.35492888, -0.61215194],
        [-0.35440934, -0.57125482, -0.74031207]]))

In [38]:
np.dot(matrix, matrix*2)

array([[ 4050,  7936, 11720],
       [ 4752,  9962, 10148],
       [ 6776, 14820, 17618]])

In [39]:
np.cross(matrix, matrix*2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
linalg.matrix_rank(matrix)

3

In [41]:
np.sin(matrix)

array([[-0.8462204 ,  0.99060736, -0.55878905],
       [-0.00885131, -0.521551  , -0.66363388],
       [-0.00885131,  0.39592515,  0.51397846]])

In [42]:
np.cos(matrix)

array([[-0.53283302,  0.13673722, -0.82930983],
       [-0.99996083,  0.85322011, -0.74805753],
       [-0.99996083, -0.91828279, -0.85780309]])

In [43]:
np.tan(matrix)

array([[ 1.58815308,  7.24460662,  0.6738001 ],
       [ 0.00885166, -0.61127369,  0.88714284],
       [ 0.00885166, -0.4311582 , -0.59918   ]])

In [44]:
matrix

array([[23, 14, 54],
       [22, 56, 29],
       [22, 53, 78]])

In [45]:
matrix.T

array([[23, 22, 22],
       [14, 56, 53],
       [54, 29, 78]])

In [47]:
np.transpose(matrix)

array([[23, 22, 22],
       [14, 56, 53],
       [54, 29, 78]])

### Array Manipulation

In [48]:
matrix.shape

(3, 3)

In [49]:
matrix.reshape(1, 9)

array([[23, 14, 54, 22, 56, 29, 22, 53, 78]])

In [50]:
mat1 = np.array(
    [[28, 19, 59, 32, 72, 59],
    [27, 61, 34, 75, 28, 72],
    [27, 58, 83, 19, 68, 90],
    [26, 58, 69, 57, 84, 99]])

In [51]:
mat1.shape

(4, 6)

In [52]:
mat1.reshape(6, 4)

array([[28, 19, 59, 32],
       [72, 59, 27, 61],
       [34, 75, 28, 72],
       [27, 58, 83, 19],
       [68, 90, 26, 58],
       [69, 57, 84, 99]])

In [53]:
mat1.ravel()

array([28, 19, 59, 32, 72, 59, 27, 61, 34, 75, 28, 72, 27, 58, 83, 19, 68,
       90, 26, 58, 69, 57, 84, 99])

In [54]:
mat1.flatten()

array([28, 19, 59, 32, 72, 59, 27, 61, 34, 75, 28, 72, 27, 58, 83, 19, 68,
       90, 26, 58, 69, 57, 84, 99])

In [55]:
# argmax() function returns indices of max element of array
# max value mat1 is 99 and it's index is 23 
mat1.argmax()

23

In [56]:
# index number of max values row wise
mat1.argmax(axis=0)

array([0, 1, 2, 1, 3, 3], dtype=int64)

In [57]:
# index number of min values row wise
mat1.argmin(axis=0)

array([3, 0, 1, 2, 1, 0], dtype=int64)

In [58]:
# index number of max values column wise
mat1.argmax(axis=1)

array([4, 3, 5, 5], dtype=int64)

In [59]:
mat1

array([[28, 19, 59, 32, 72, 59],
       [27, 61, 34, 75, 28, 72],
       [27, 58, 83, 19, 68, 90],
       [26, 58, 69, 57, 84, 99]])

In [60]:
# sorting max values by index in row wise
mat1.argsort(axis=0)

array([[3, 0, 1, 2, 1, 0],
       [1, 2, 0, 0, 2, 1],
       [2, 3, 3, 3, 0, 2],
       [0, 1, 2, 1, 3, 3]], dtype=int64)

In [61]:
mat1.shape

(4, 6)

In [62]:
mat1.reshape(2, 3, 2, 2)

array([[[[28, 19],
         [59, 32]],

        [[72, 59],
         [27, 61]],

        [[34, 75],
         [28, 72]]],


       [[[27, 58],
         [83, 19]],

        [[68, 90],
         [26, 58]],

        [[69, 57],
         [84, 99]]]])

In [63]:
mat1.dtype

dtype('int32')

In [64]:
mat1.astype(np.complex_)

array([[28.+0.j, 19.+0.j, 59.+0.j, 32.+0.j, 72.+0.j, 59.+0.j],
       [27.+0.j, 61.+0.j, 34.+0.j, 75.+0.j, 28.+0.j, 72.+0.j],
       [27.+0.j, 58.+0.j, 83.+0.j, 19.+0.j, 68.+0.j, 90.+0.j],
       [26.+0.j, 58.+0.j, 69.+0.j, 57.+0.j, 84.+0.j, 99.+0.j]])

In [66]:
mat1

array([[28, 19, 59, 32, 72, 59],
       [27, 61, 34, 75, 28, 72],
       [27, 58, 83, 19, 68, 90],
       [26, 58, 69, 57, 84, 99]])

In [65]:
# horizontal split
np.hsplit(mat1, 2)

[array([[28, 19, 59],
        [27, 61, 34],
        [27, 58, 83],
        [26, 58, 69]]),
 array([[32, 72, 59],
        [75, 28, 72],
        [19, 68, 90],
        [57, 84, 99]])]

In [67]:
# vertical split
np.vsplit(mat1, 2)

[array([[28, 19, 59, 32, 72, 59],
        [27, 61, 34, 75, 28, 72]]),
 array([[27, 58, 83, 19, 68, 90],
        [26, 58, 69, 57, 84, 99]])]

In [68]:
np.vstack((np.arange(1,5), np.arange(1,5)**2, np.arange(1,5)**3))

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16],
       [ 1,  8, 27, 64]])

In [69]:
np.hstack((np.arange(1,5), np.arange(1,5)**2, np.arange(1,5)**3))

array([ 1,  2,  3,  4,  1,  4,  9, 16,  1,  8, 27, 64])