In [2]:
import numpy as np
import pandas as pd

In [3]:
# Generate array of ‘100’ random numbers sampled from a standard normal distribution using Numpy
x = np.random.rand(100)
print(x)

[0.35253834 0.27461705 0.9741356  0.27755132 0.19298987 0.72537888
 0.81311655 0.62599844 0.47374824 0.7953357  0.15430327 0.94263914
 0.81254334 0.41313383 0.8777241  0.51947929 0.37958951 0.96498591
 0.8645628  0.78487941 0.52309611 0.89147086 0.98959195 0.74198529
 0.24737899 0.11392995 0.7561687  0.03755976 0.31555173 0.9736853
 0.49116586 0.43035045 0.74096347 0.35617876 0.89051812 0.93298352
 0.33042612 0.96471591 0.74931772 0.5181578  0.04494429 0.1491907
 0.99757916 0.2423541  0.88298979 0.05257878 0.00241445 0.15410186
 0.01032013 0.49131531 0.58228127 0.30504169 0.6755875  0.58724299
 0.53761275 0.06226033 0.67045579 0.57708735 0.06627144 0.85642038
 0.12883754 0.55469088 0.8114345  0.16328685 0.98132325 0.0833526
 0.95432884 0.52111499 0.85821773 0.74812115 0.10833575 0.26115632
 0.80053235 0.62402748 0.79075897 0.00264397 0.88038006 0.44412825
 0.61794395 0.2236371  0.03844065 0.10022978 0.87300513 0.96608569
 0.18341878 0.98255556 0.96484928 0.91968801 0.64669662 0.4489704

In [6]:
print(np.std(x))
print(np.var(x))
print(np.mean(x))

0.3132008383549227
0.09809476514622642
0.5437939500931601


In [7]:
print(x.mean())

0.5437939500931601


In [8]:
# How to count the occurrence of each value in a numpy array?
arr = np.array([0, 5, 5, 0, 2, 4, 3, 0, 0, 5, 4, 1, 9, 9])
np.bincount(arr)
# The argument to bincount() must consist of booleans or positive integers. Negative integers are invalid

array([4, 1, 1, 1, 2, 3, 0, 0, 0, 2], dtype=int64)

In [9]:
# How to remove from one array those items that exist in another?
a = np.array([5, 4, 3, 2, 1])
b = np.array([4, 8, 9, 10, 1])
# From 'a' remove all of 'b'
np.setdiff1d(a,b)
# Output: array([5, 3, 2])

array([2, 3, 5])

In [10]:
# How to sort a numpy array by a specific column in a 2D array?
# Choose column 2 as an example
arr = np.array([[1, 2, 3], [4, 5, 6], [0,0,1]])
arr[arr[:,1].argsort()]
# Output : array([[0, 0, 1], [1, 2, 3], [4, 5, 6]])

array([[0, 0, 1],
       [1, 2, 3],
       [4, 5, 6]])

In [12]:
# How to reverse a numpy array in the most efficient way?
arr = np.array([9, 10, 1, 2, 0])
reverse_arr = arr[::-1]
reverse_arr

array([ 0,  2,  1, 10,  9])

In [13]:
# How to calculate percentiles when using numpy?
arr = np.array([11, 22, 33, 44, 55, 66, 77])
perc = np.percentile(arr, 40) #Returns the 40th percentile
print(perc)

37.400000000000006


In [15]:
# What Is The Preferred Way To Check For An Empty (zero Element) Array?
# For a numpy array, use the size attribute. The size attribute is helpful for determining the length of numpy array:
arr = np.zeros((1,0))
arr.size

0

In [16]:
# How can you find the indices of an array where a condition is true?
# Given an array a, the condition arr > 3 returns a boolean array and since False is
# interpreted as 0 in Python and NumPy.
arr = np.array([[9,8,7],[6,5,4],[3,2,1]])
arr > 3

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [18]:
# How to find the maximum and minimum value of a given flattened array?
a = np.arange(4).reshape((2,2))
print(a)
max_val = np.amax(a)
min_val = np.amin(a)
print(max_val)
print(min_val)

[[0 1]
 [2 3]]
3
0


In [24]:
# Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
arr = np.arange(16).reshape((4, 4))
print(arr)
res = np.ptp(arr, 1)
res

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([3, 3, 3, 3])

In [25]:
res = np.ptp(arr, 0)
res

array([12, 12, 12, 12])

In [27]:
# Find median of a numpy flattened array
arr = np.arange(16).reshape((4, 4))
print(arr)
res = np.median(arr)
res

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


7.5

In [28]:
# Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis
x = np.arange(16)
print(x)
mean = np.mean(x)
print(mean)
std = np.std(x)
print(std)
var= np.var(x)
print(var)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
7.5
4.6097722286464435
21.25


In [29]:
# Calculate covariance matrix between two numpy arrays
x = np.array([2, 1, 0])
y = np.array([2, 3, 3])
print(x)
print(y)
cov_arr = np.cov(x, y)
print(cov_arr)

[2 1 0]
[2 3 3]
[[ 1.         -0.5       ]
 [-0.5         0.33333333]]


In [30]:
# Compute pearson product-moment correlation coefficients of two given numpy arrays
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print(x)
print(y)
cross_corr = np.corrcoef(x, y)
print(cross_corr)

[0 1 3]
[2 4 5]
[[1.         0.92857143]
 [0.92857143 1.        ]]


In [31]:
# Develop a numpy program to compute the histogram of nums against the bins
nums = np.array([0.5, 0.7, 1.0, 1.2, 1.3, 2.1])
bins = np.array([0, 1, 2, 3])
np.histogram(nums, bins)

(array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [32]:
# Get the powers of an array values element-wise
x = np.arange(7)
print(x)
np.power(x, 3)

[0 1 2 3 4 5 6]


array([  0,   1,   8,  27,  64, 125, 216], dtype=int32)

In [33]:
# Write a NumPy program to get true division of the element-wise array inputs
x = np.arange(10)
print(x)
np.true_divide(x, 3)

[0 1 2 3 4 5 6 7 8 9]


array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [34]:
# How will you create a series from dict in Pandas?
# A Series is defined as a one-dimensional array that is capable of storing various data types.
info = {'x' : 0., 'y' : 1., 'z' : 2.}
a = pd.Series(info)
a

x    0.0
y    1.0
z    2.0
dtype: float64

In [ ]:
# How can we create a copy of the series in Pandas?
pd.Series.copy(deep=True)

In [35]:
# Write a Pandas program to get the first 5 rows of a given DataFrame
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael',
'Matthew', 'Laura', 'Kevin', 'Jonas'],}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data , index=labels)
df.iloc[:5]

name
a  Anastasia
b       Dima
c  Katherine
d      James
e      Emily

In [37]:
# Develop a Pandas program to create and display a one-dimensional arraylike object containing an array of data.
pd.Series([2, 4, 6, 8, 10])

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [38]:
# Write a Python program to convert a Panda module Series to Python list and it's type.
ds = pd.Series([2, 4, 6, 8, 10])
print(type(ds))
s = ds.tolist()
type(s)

<class 'pandas.core.series.Series'>


list

In [39]:
# Develop a Pandas program to add, subtract, multiple and divide two Pandas Series.
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
sum = ds1 + ds2
sub = ds1 - ds2
mul = ds1 * ds2
div = ds1 / ds2
print(sum)
print(sub)
print(mul)
print(div)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [40]:
# Develop a Pandas program to compare the elements of the two Pandas Series.
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
ds1 == ds2
ds1 > ds2
ds1 < ds2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [41]:
# Develop a Pandas program to change the data type of given a column or a Series.
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
s2 = pd.to_numeric(s1, errors='coerce')
s2

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

In [43]:
# Write a Pandas program to convert Series of lists to one Series
s = pd.Series([ ['Red', 'Black'], ['Red', 'Green', 'White'] , ['Yellow']])
print(s)
s = s.apply(pd.Series).stack().reset_index(drop=True)
s

0           [Red, Black]
1    [Red, Green, White]
2               [Yellow]
dtype: object


0       Red
1     Black
2       Red
3     Green
4     White
5    Yellow
dtype: object

In [44]:
# Write a Pandas program to create a subset of a given series based on value and condition
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
n = 6
new_s = s[s < n]
new_s

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [45]:
# Develop a Pandas code to alter the order of index in a given series
s = pd.Series(data = [1,2,3,4,5], index = ['A','B','C','D','E'])
s.reindex(index = ['B','A','C','D','E'])

B    2
A    1
C    3
D    4
E    5
dtype: int64

In [46]:
# Write a Pandas code to get the items of a given series not present in another given series.
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
result = sr1[~sr1.isin(sr2)]
result

0    1
2    3
4    5
dtype: int64

In [59]:
# Write a Pandas program to display the most frequent value in a given series and replace everything else as “replaced” in the series.
np.random.RandomState(100)
num_series = pd.Series(np.random.randint(1, 5, [15]))
print(num_series)
#result = num_series[~num_series.isin(num_series.value_counts().index[:1])] # = 'replaced'
result1 = num_series[~num_series.isin(num_series.value_counts().index[:1])]
result1

0     3
1     4
2     4
3     1
4     4
5     4
6     2
7     1
8     1
9     3
10    1
11    3
12    1
13    1
14    4
dtype: int32


0     3
1     4
2     4
4     4
5     4
6     2
9     3
11    3
14    4
dtype: int32

In [66]:
# Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
#num_series = pd.Series(np.random.randint(1, 10, 9))
num_series = np.random.randint(1, 10, 9)
print(num_series)
#result = np.argwhere(num_series % 5==0)
result = np.argwhere(num_series % 5==0)
result

[1 9 4 5 9 9 6 2 2]


array([[3]], dtype=int64)

In [68]:
# How will you add a column to a pandas DataFrame?
info = {'one' : pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']),
'two' : pd.Series([1, 2, 3, 4, 5, 6], index=['a', 'b', 'c', 'd', 'e', 'f'])}
info = pd.DataFrame(info)
# Add a new column to an existing DataFrame object
info['three'] = pd.Series([20,40,60],index=['a','b','c'])
info

one  two  three
a  1.0    1   20.0
b  2.0    2   40.0
c  3.0    3   60.0
d  4.0    4    NaN
e  5.0    5    NaN
f  NaN    6    NaN

In [77]:
# How to iterate over a Pandas DataFrame?
# You can iterate over the rows of the DataFrame by using for loop in combination with an iterrows() call on the DataFrame.
for i, j in info.iterrows():
    print(j['three'])

20.0
40.0
60.0
nan
nan
nan


In [74]:
data = {
  "firstname": ["Sally", "Mary", "John"],
  "age": [50, 40, 30]
}

df = pd.DataFrame(data)
print(df)
for index, row in df.iterrows():
  print(row["firstname"])

  firstname  age
0     Sally   50
1      Mary   40
2      John   30
Sally
Mary
John
