<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#basic-example" data-toc-modified-id="basic-example-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>basic example</a></span><ul class="toc-item"><li><span><a href="#Loading-librarys" data-toc-modified-id="Loading-librarys-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Loading librarys</a></span></li><li><span><a href="#importing-nltk-librarys" data-toc-modified-id="importing-nltk-librarys-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>importing nltk librarys</a></span><ul class="toc-item"><li><span><a href="#tokenization" data-toc-modified-id="tokenization-1.2.1"><span class="toc-item-num">1.2.1&nbsp;&nbsp;</span>tokenization</a></span></li><li><span><a href="#stopwords,-stemming-and-lemmatization" data-toc-modified-id="stopwords,-stemming-and-lemmatization-1.2.2"><span class="toc-item-num">1.2.2&nbsp;&nbsp;</span>stopwords, stemming and lemmatization</a></span></li><li><span><a href="#Bag-OF-Words-(BOW)" data-toc-modified-id="Bag-OF-Words-(BOW)-1.2.3"><span class="toc-item-num">1.2.3&nbsp;&nbsp;</span>Bag OF Words (BOW)</a></span></li><li><span><a href="#TFIDF" data-toc-modified-id="TFIDF-1.2.4"><span class="toc-item-num">1.2.4&nbsp;&nbsp;</span>TFIDF</a></span></li></ul></li></ul></li><li><span><a href="#Word-Embedding-Techniques" data-toc-modified-id="Word-Embedding-Techniques-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Word Embedding Techniques</a></span><ul class="toc-item"><li><span><a href="#using-Embedding-Layer-in-Keras" data-toc-modified-id="using-Embedding-Layer-in-Keras-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>using Embedding Layer in Keras</a></span><ul class="toc-item"><li><span><a href="#One-Hot-Representation" data-toc-modified-id="One-Hot-Representation-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>One Hot Representation</a></span></li><li><span><a href="#Word-Embedding-Represntation" data-toc-modified-id="Word-Embedding-Represntation-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Word Embedding Represntation</a></span></li></ul></li></ul></li></ul></div>

# basic example

## Loading librarys

In [1]:
import pandas as pd
import numpy as np

In [3]:
paragraph="""Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); 
born 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. 
Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. 
He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer 
organisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the 
Indian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. 
He is also the longest serving prime minister from a non-Congress party.
Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. 
He was introduced to the RSS at age eight. He has drawn attention to having to work as a child in his father's tea stall on the 
Vadnagar railway station platform, a description that has not been reliably corroborated. At age 18, Modi was married to Jashodaben Chimanlal Modi, 
whom he abandoned soon after. He left his parental home where she had come to live. He first publicly acknowledged her as his wife more than 
four decades later when required to do so by Indian law, but has made no contact with her since. Modi has asserted he had travelled in northern India 
for two years after leaving his parental home, visiting a number of religious centres, but few details of his travels have emerged. 
Upon his return to Gujarat in 1971, he became a full-time worker for the RSS. After the state of emergency was declared by prime minister 
Indira Gandhi in 1975, Modi went into hiding. The RSS assigned him to the BJP in 1985 and he held several positions within 
the party hierarchy until 2001, rising to the rank of general secretary.[b]
"""

In [4]:
paragraph

"Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); \nborn 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014. \nModi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi. \nHe is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer \norganisation. He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the \nIndian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament. \nHe is also the longest serving prime minister from a non-Congress party.\nBorn and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there. \nHe was introduced to the RSS at age eight. He has drawn attention to havin

## importing nltk librarys

In [4]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

### tokenization

In [5]:
# tokenization converts paragraph-sentences-words
# Punkt is a Tokenizer Model
nltk.download('punkt')
sentences = nltk.sent_tokenize(paragraph)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SHEHA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [6]:
print(sentences)

['Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] (listen); \nborn 17 September 1950)[a] is an Indian politician serving as the 14th and current prime minister of India since 2014.', 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament from Varanasi.', 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right-wing Hindu nationalist paramilitary volunteer \norganisation.', "He is the first prime minister to have been born after India's independence in 1947 and the second prime minister not belonging to the \nIndian National Congress to have won two consecutive majorities in the Lok Sabha, or the lower house of India's parliament.", 'He is also the longest serving prime minister from a non-Congress party.', 'Born and raised in Vadnagar, a small town in northeastern Gujarat, Modi completed his secondary education there.', 'He was introduced to the RSS at age eight.', "He has drawn atten

In [7]:
len(sentences)

16

In [8]:
import re
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i]) # replacing symbols and characters with white space
    review=review.lower()
    corpus.append(review)

In [9]:
corpus

['narendra damodardas modi  gujarati    n  end   d mod   d s  modi    listen    born    september       a  is an indian politician serving as the   th and current prime minister of india since      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament from varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer  organisation ',
 'he is the first prime minister to have been born after india s independence in      and the second prime minister not belonging to the  indian national congress to have won two consecutive majorities in the lok sabha  or the lower house of india s parliament ',
 'he is also the longest serving prime minister from a non congress party ',
 'born and raised in vadnagar  a small town in northeastern gujarat  modi completed his secondary education there ',
 'he was introduced to the rss at age eight ',
 'he has drawn a

### stopwords, stemming and lemmatization

In [10]:
# downloding stopwords package
nltk.download('stopwords')
stopwords.words('english')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SHEHA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [11]:
# sample code of stemming
stemmer = PorterStemmer()
stemmer.stem('history')

'histori'

In [12]:
# sample code of lemmatizer, takes meaningful word
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SHEHA\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
# sample code of lemmatizer
lemmatizer = WordNetLemmatizer()
lemmatizer.lemmatize('goes')

'go'

In [14]:
# sample code of stemminng in corpus
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

narendra
damodarda
modi
gujarati
n
end
mod
modi
listen
born
septemb
indian
politician
serv
th
current
prime
minist
india
sinc
modi
chief
minist
gujarat
member
parliament
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
first
prime
minist
born
india
independ
second
prime
minist
belong
indian
nation
congress
two
consecut
major
lok
sabha
lower
hous
india
parliament
also
longest
serv
prime
minist
non
congress
parti
born
rais
vadnagar
small
town
northeastern
gujarat
modi
complet
secondari
educ
introduc
rss
age
eight
drawn
attent
work
child
father
tea
stall
vadnagar
railway
station
platform
descript
reliabl
corrobor
age
modi
marri
jashodaben
chimanl
modi
abandon
soon
left
parent
home
come
live
first
publicli
acknowledg
wife
four
decad
later
requir
indian
law
made
contact
sinc
modi
assert
travel
northern
india
two
year
leav
parent
home
visit
number
religi
centr
detail
travel
emerg
upon
return
gujarat
becam
full

In [15]:
# sample code of lemmatization in corpus 
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

narendra
damodardas
modi
gujarati
n
end
mod
modi
listen
born
september
indian
politician
serving
th
current
prime
minister
india
since
modi
chief
minister
gujarat
member
parliament
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
first
prime
minister
born
india
independence
second
prime
minister
belonging
indian
national
congress
two
consecutive
majority
lok
sabha
lower
house
india
parliament
also
longest
serving
prime
minister
non
congress
party
born
raised
vadnagar
small
town
northeastern
gujarat
modi
completed
secondary
education
introduced
r
age
eight
drawn
attention
work
child
father
tea
stall
vadnagar
railway
station
platform
description
reliably
corroborated
age
modi
married
jashodaben
chimanlal
modi
abandoned
soon
left
parental
home
come
live
first
publicly
acknowledged
wife
four
decade
later
required
indian
law
made
contact
since
modi
asserted
travelled
northern
india
two
year
leaving
pare

In [16]:
# main code
# Apply Stopswords and lemmatization in corpus, not recommanded to use stemming as it results in lose of meaningful words
import re
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

### Bag OF Words (BOW)

In [17]:
# Bag OF Words - converting word to vector
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True)

In [18]:
X = cv.fit_transform(corpus)

In [19]:
cv.vocabulary_

{'narendra': 71,
 'damodardas': 23,
 'modi': 70,
 'gujarati': 41,
 'end': 33,
 'mod': 69,
 'listen': 59,
 'born': 11,
 'september': 103,
 'indian': 50,
 'politician': 84,
 'serving': 104,
 'th': 114,
 'current': 22,
 'prime': 86,
 'minister': 68,
 'india': 49,
 'since': 106,
 'chief': 13,
 'gujarat': 40,
 'member': 67,
 'parliament': 81,
 'varanasi': 122,
 'bharatiya': 9,
 'janata': 53,
 'party': 82,
 'bjp': 10,
 'rashtriya': 91,
 'swayamsevak': 112,
 'sangh': 99,
 'right': 96,
 'wing': 127,
 'hindu': 45,
 'nationalist': 73,
 'paramilitary': 79,
 'volunteer': 124,
 'organisation': 78,
 'first': 35,
 'independence': 48,
 'second': 100,
 'belonging': 8,
 'national': 72,
 'congress': 18,
 'two': 119,
 'consecutive': 19,
 'majority': 65,
 'lok': 61,
 'sabha': 98,
 'lower': 63,
 'house': 47,
 'also': 3,
 'longest': 62,
 'non': 74,
 'raised': 89,
 'vadnagar': 121,
 'small': 107,
 'town': 116,
 'northeastern': 75,
 'completed': 17,
 'secondary': 101,
 'education': 29,
 'introduced': 52,
 'age

In [20]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september indian politician serving th current prime minister india since'

In [21]:
X[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [22]:
type(X)

scipy.sparse._csr.csr_matrix

### TFIDF

In [23]:
# TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(ngram_range=(1,1),max_features=10)
X = cv.fit_transform(corpus)

In [24]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi listen born september indian politician serving th current prime minister india since'

In [25]:
X[0].toarray()

array([[0.38064993, 0.        , 0.38064993, 0.38064993, 0.        ,
        0.31757459, 0.5871889 , 0.        , 0.        , 0.34593707]])

# Word Embedding Techniques 

## using Embedding Layer in Keras

In [2]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [3]:
# sample text
sent=[ 'the glass of milk','the glass of juice','the cup of tea','I am a good boy','I am a good developer',
      'understand the meaning of words','your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# giving random Vocabulary size
voc_size=500

### One Hot Representation

In [5]:
from tensorflow.keras.preprocessing.text import one_hot
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[40, 88, 197, 99], [40, 88, 197, 315], [40, 377, 197, 132], [237, 359, 407, 99, 498], [237, 359, 407, 99, 241], [456, 40, 39, 197, 411], [226, 450, 431, 99]]


### Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

# pre padding
sent_length=8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)  
print(embedded_docs)

[[  0   0   0   0  40  88 197  99]
 [  0   0   0   0  40  88 197 315]
 [  0   0   0   0  40 377 197 132]
 [  0   0   0 237 359 407  99 498]
 [  0   0   0 237 359 407  99 241]
 [  0   0   0 456  40  39 197 411]
 [  0   0   0   0 226 450 431  99]]


In [7]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))  # 10 is feature dimesnions
model.compile('adam','mse')

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [9]:
embedded_docs[0]

array([  0,   0,   0,   0,  40,  88, 197,  99])

In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 15ms/step


array([[[-1.03948265e-03,  1.87656023e-02, -1.57324076e-02,
         -6.83368370e-03,  2.39395387e-02, -3.53184938e-02,
         -2.77746841e-03,  6.15650415e-03,  4.19757999e-02,
         -2.23286394e-02],
        [-1.03948265e-03,  1.87656023e-02, -1.57324076e-02,
         -6.83368370e-03,  2.39395387e-02, -3.53184938e-02,
         -2.77746841e-03,  6.15650415e-03,  4.19757999e-02,
         -2.23286394e-02],
        [-1.03948265e-03,  1.87656023e-02, -1.57324076e-02,
         -6.83368370e-03,  2.39395387e-02, -3.53184938e-02,
         -2.77746841e-03,  6.15650415e-03,  4.19757999e-02,
         -2.23286394e-02],
        [-1.03948265e-03,  1.87656023e-02, -1.57324076e-02,
         -6.83368370e-03,  2.39395387e-02, -3.53184938e-02,
         -2.77746841e-03,  6.15650415e-03,  4.19757999e-02,
         -2.23286394e-02],
        [-3.07695996e-02, -2.20198873e-02, -4.31358702e-02,
          3.68328951e-02, -2.53195055e-02,  7.59583712e-03,
          3.23968790e-02,  1.43244751e-02, -2.000335

In [13]:
embedded_docs[0]

array([  0,   0,   0,   0,  40,  88, 197,  99])

In [14]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 13ms/step
[[-0.00103948  0.0187656  -0.01573241 -0.00683368  0.02393954 -0.03531849
  -0.00277747  0.0061565   0.0419758  -0.02232864]
 [-0.00103948  0.0187656  -0.01573241 -0.00683368  0.02393954 -0.03531849
  -0.00277747  0.0061565   0.0419758  -0.02232864]
 [-0.00103948  0.0187656  -0.01573241 -0.00683368  0.02393954 -0.03531849
  -0.00277747  0.0061565   0.0419758  -0.02232864]
 [-0.00103948  0.0187656  -0.01573241 -0.00683368  0.02393954 -0.03531849
  -0.00277747  0.0061565   0.0419758  -0.02232864]
 [-0.0307696  -0.02201989 -0.04313587  0.0368329  -0.02531951  0.00759584
   0.03239688  0.01432448 -0.02000335  0.00406234]
 [-0.00566418  0.01938951  0.01197723 -0.04561196 -0.00573238  0.00937454
  -0.00046702  0.00203894  0.01561833  0.04562414]
 [ 0.00386425  0.00227205  0.00256966  0.0153816  -0.04836104  0.01838866
  -0.0417137   0.04691279  0.04730297 -0.04677861]
 [ 0.03563286  0.03082407  0.01286111  0.01872266 -0.0294315   0.02657199

In [ ]:
# Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"]